name: ci

on:
  push:
    branches:
      - main
      - master
      - dev
  pull_request:
    branches:
      - main
      - master
      - dev
      
jobs:
  ci:
    strategy:
      matrix:
        os: [ubuntu-latest]
        node: [18]
  
    runs-on: ${{ matrix.os }}
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3 # v3.3.0
        
      - name: Setup Node.js environment
        uses: actions/setup-node@3 # v3.6.0
        with:
          node-version: ${{ matrix.os }}
          cache: 'pnpm'
          
      - name: Setup pnpm
        uses: pnpm/action-setup@2 # v2.2.4
        with:
          version: 7
          run_install: false
          
      - name: Get pnpm store directory
        id: pnpm-cache
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT
          
      - name: Setup pnpm cache
        uses: actions/cache@v3 # v3.2.6
        with:
          path: ${{ steps.pnpm-cache.outputs.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-
            
      - name: Install dependencies
        run: pnpm install
      
      - name: Run linter
        run: pnpm lint
